1.	Create a python program to find duplicate files by content. User will input path and it will scan all directories, sub-directories to find all duplicates files.
Delete the found duplicate file.
[Hint: use hashlib]


In [1]:
import os
import hashlib

def find_duplicate_files(path):
    # create a dictionary to store file hashes and their paths
    file_dict = {}

    # traverse through all files and subdirectories in the given path
    for dirpath, dirnames, filenames in os.walk(path):
        for filename in filenames:
            # calculate hash of the current file
            file_path = os.path.join(dirpath, filename)
            with open(file_path, "rb") as f:
                file_hash = hashlib.sha256(f.read()).hexdigest()

            # add the file path to the dictionary
            if file_hash in file_dict:
                file_dict[file_hash].append(file_path)
            else:
                file_dict[file_hash] = [file_path]

    # return the list of duplicate files
    return [paths for paths in file_dict.values() if len(paths) > 1]

def delete_duplicate_files(duplicate_files):
    for file_paths in duplicate_files:
        # keep the first file and delete the rest
        for path in file_paths[1:]:
            os.remove(path)

if __name__ == "__main__":
    # get the path from the user
    path = input("Enter the path to scan: ")

    # find duplicate files
    duplicate_files = find_duplicate_files(path)

    if duplicate_files:
        print("Found duplicate files:")
        for file_paths in duplicate_files:
            print(file_paths)
        
        # ask for confirmation before deleting files
        confirm = input("Do you want to delete the duplicate files? (y/n): ")
        if confirm.lower() == "y":
            delete_duplicate_files(duplicate_files)
            print("Duplicate files deleted.")
        else:
            print("Duplicate files not deleted.")
    else:
        print("No duplicate files found.")

Enter the path to scan: C:\Users\cmunagala\Desktop\python
No duplicate files found.


2.	Generate random Password with exact length = 6, with minimum 1 uppercase, 2 lowercase, 2 digits, and remaining special characters.
Using these packages [random, strings]


In [8]:
import random
import string
# define the password length and character requirements
password_length = 6
uppercase_letters = 1
lowercase_letters = 2
digits = 2

# define the character sets for each category
uppercase_set = string.ascii_uppercase
lowercase_set = string.ascii_lowercase
digit_set = string.digits
special_set = string.punctuation

# initialize the password as an empty string
password = ""

# choose one uppercase letter at random and add it to the password
password += random.choice(uppercase_set)

# choose two lowercase letters at random and add them to the password
for i in range(lowercase_letters):
    password += random.choice(lowercase_set)

# choose two digits at random and add them to the password
for i in range(digits):
    password += random.choice(digit_set)

# choose the remaining characters at random from all the sets and add them to the password
remaining_length = password_length - uppercase_letters - lowercase_letters - digits
for i in range(remaining_length):
    password += random.choice(uppercase_set + lowercase_set + digit_set + special_set)

# shuffle the password to make it more random
password_list = list(password)
random.shuffle(password_list)
password = "".join(password_list)

# print the password
print("Random password: ", password)

Random password:  n7E4kf


3.	Create 2D array and update the same 2D array provided that every prime number position should be replaced by cube of the positioned number.

In [4]:
import math

# Create a 2D array of size n x m
n = 5
m = 5
arr = [[0 for j in range(m)] for i in range(n)]
# Update the array by replacing prime number positions with cube of positioned number
for i in range(n):
    for j in range(m):
        num = i * m + j + 1  # Get the number corresponding to the position
        if is_prime(num):
            arr[i][j] = num ** 3


# Print the updated array
print(arr)

# Function to check if a number is prime
def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(math.sqrt(num))+1):
        if num % i == 0:
            return False
    return True



[[0, 8, 27, 0, 125], [0, 343, 0, 0, 0], [1331, 0, 2197, 0, 0], [0, 4913, 0, 6859, 0], [0, 0, 12167, 0, 0]]


4.	Python program to get the sum of every cubed value and its previous integer. 

In [6]:
def sum_cubed_plus_prev(n):
    total = 0
    for i in range(1, n+1):
        total += i**3 + (i-1)
    return total


In [7]:
sum_cubed_plus_prev(5)  

235

5.	Given two arrays, find their intersection. Examples:

Input:  arr1[] = [1, 3, 4, 5, 7]
        arr2[] = [2, 3, 5, 6]


In [5]:
arr1 = [1, 3, 4, 5, 7]
arr2 = [2, 3, 5, 6]
arr_3 = []
for i in arr1:
    if i in arr2:
        arr_3.append(element)
print("Intersection of the lists is:", arr_3)

Intersection of the lists is: [3, 5]


6.	Create a 7 x 7  2D array having only multiples of 7. And return the last element of the same.

In [6]:
array_2d = [[0 for i in range(7)] for j in range(7)]

# fill the array with multiples of 7
for i in range(7):
    for j in range(7):
        array_2d[i][j] = (i+1) * (j+1) * 7

# print the array
print(array_2d)

# return the last element of the array
last_element = array_2d[6][6]
print("Last element of the array: ", last_element)

[[7, 14, 21, 28, 35, 42, 49], [14, 28, 42, 56, 70, 84, 98], [21, 42, 63, 84, 105, 126, 147], [28, 56, 84, 112, 140, 168, 196], [35, 70, 105, 140, 175, 210, 245], [42, 84, 126, 168, 210, 252, 294], [49, 98, 147, 196, 245, 294, 343]]
Last element of the array:  343



7.	Checker Board Patten using Numpy:
[   1   0   1   0   1   0   1
    0   1   0   1   0   1   0
    1   0   1   0   1   0   1
    0   1   0   1   0   1   0
    1   0   1   0   1   0   1  ]


In [9]:

import numpy as np

pattern = np.zeros((5, 7), dtype=int)  # create an n x n matrix of zeros

# set every other element to 1
pattern[::2, ::2] = 1
pattern[1::2, 1::2] = 1

print(pattern)


[[1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1]]



8.	Create a given Matrix:
[  A,   B,     C,       D
   E,      F,     G,       H
    I,      a,      K,       L
   M,    N,     o,       P
   Q,     R,      S,       T
   U,     0,     W,      O ]

Replace all the vowels by np.nan
A, E, I, O U  -- >  np.nan
Return the count of the missing values


In [14]:
import numpy as np

# create the matrix
matrix = np.array([['A', 'B', 'C', 'D'],
                   ['E', 'F', 'G', 'H'],
                   ['I', 'a', 'K', 'L'],
                   ['M', 'N', 'o', 'P'],
                   ['Q', 'R', 'S', 'T'],
                   ['U', '0', 'W', 'O']])

# replace vowels with empty string
vowels = ['A', 'E', 'I', 'O', 'U']
for vowel in vowels:
    matrix[matrix == vowel] = ''

# count missing values
count_missing = np.count_nonzero(matrix == '')

print(matrix)
print("Count of missing values:", count_missing)


[['' 'B' 'C' 'D']
 ['' 'F' 'G' 'H']
 ['' 'a' 'K' 'L']
 ['M' 'N' 'o' 'P']
 ['Q' 'R' 'S' 'T']
 ['' '0' 'W' '']]
Count of missing values: 5
